tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'

brew 'imagemagick'
brew 'mysql'
brew 'openssl'
brew 'curl'
brew 'wget'
brew 'git'
brew 'nvm'
brew 'php55'
brew 'composer'
brew 'mongodb'
brew 'graphicsmagick'
brew 'dnsmasq'
